INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Biscuit", 10, "images\\biscuit.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Brownie", 15, "images\\brownie.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cake", 10, "images\\cake.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Casserole",15, "images\\casserole.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cookie", 20, "images\\CookieProxypng");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cracker", 25, "images\\cracker.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Custard", 10, "images\\custard.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pastry", 30, "images\\pastry.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pie", 10, "images\\pie.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pudding", 10, "images\\pudding.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Tart", 5, "images\\tart.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Arepa", 10, "images\\arepa.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Bagel", 15, "images\\bagel.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Bammy", 10, "images\\bammy.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Breadstick",15, "images\\breadstick.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Brown Bread", 20, "images\\brown_bread.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Canadian White", 25, "images\\canadian_white.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Chapati", 10, "images\\chapati.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Khakhra", 30, "images\\khakhra.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Kulcha", 10, "images\\kulcha.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Naan", 20, "images\\naan.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Papad",40, "images\\papad.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Paratha", 25, "images\\paratha.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pizza", 30, "images\\pizza.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Roti", 35, "images\\roti.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "White Bread", 20, "images\\white_bread.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Black Tea", 10, "images\\black_tea.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Coca Cola", 10, "images\\coca_cola.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Coffee", 15, "images\\coffee.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Fanta", 10, "images\\fanta.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Frooti",15, "images\\frooti.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Green Tea", 20, "images\\green_tea.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Limca", 25, "images\\limca.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mirinda", 10, "images\\mirinda.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mountain Dew", 30, "images\\mountain_dew.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mazaa", 10, "images\\mazaa.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pepsi", 20, "images\\pepsi.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Red Bull",40, "images\\red_bull.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Sprite", 25, "images\\sprite.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Thumbs Up", 30, "images\\thumbs_up.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Soda", 35, "images\\soda.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Water", 20, "images\\water.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Butter", 10, "images\\butter.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Buttermilk", 15, "images\\buttermilk.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Chaas", 10, "images\\chaas.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cheese",15, "images\\cheese.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cottage Cheese", 20, "images\\cottage_cheese.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cream", 25, "images\\cream.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Curd", 10, "images\\curd.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Ghee", 30, "images\\ghee.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Ice Cream", 10, "images\\ice_cream.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Khoa", 20, "images\\khoa.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Kulfi",40, "images\\kulfi.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Lassi", 25, "images\\lassi.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Malai", 30, "images\\malai.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Milk", 35, "images\\milk.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Yogurt", 20, "images\\yogurt.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Apple", 10, "images\\apple.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Avocado", 15, "images\\avocado.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Blackberry", 10, "images\\blackberry.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Banana",15, "images\\banana.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Blueberry", 20, "images\\blueberry.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Date", 25, "images\\date.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Fig", 10, "images\\fig.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Grape", 30, "images\\grape.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Guava", 10, "images\\guava.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Jackfruit", 20, "images\\jackfruit.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Kiwifruit",40, "images\\kiwifruit.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Lemon", 25, "images\\lemon.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mango", 30, "images\\mango.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Orange", 35, "images\\orange.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Papaya", 20, "images\\papaya.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pineapple", 20, "images\\pineapple.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Peach", 20, "images\\peach.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Plum", 20, "images\\plum.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Strawberry", 20, "images\\strawberry.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Vanilla", 20, "images\\vanilla.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Watermelon", 20, "images\\watermelon.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Beef", 10, "images\\beef.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Goat", 15, "images\\goat.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Ham", 10, "images\\ham.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Lamb",15, "images\\lamb.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mutton", 20, "images\\mutton.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pork", 25, "images\\pork.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Chicken", 10, "images\\chicken.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Fish", 30, "images\\fish.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Broccoli", 10, "images\\broccoli.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cabbage", 15, "images\\cabbage.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cauliflower", 10, "images\\cauliflower.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Chickpea",15, "images\\chickpea.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Onion", 20, "images\\onion.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Tomato", 25, "images\\tomato.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Radish", 10, "images\\radish.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Carrot", 30, "images\\carrot.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Potato", 30, "images\\potato.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mushroom", 30, "images\\mushroom.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Spinach", 30, "images\\spinach.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Garlic", 30, "images\\garlic.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Ginger", 30, "images\\ginger.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Capsicum", 30, "images\\capsicum.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Turnip", 30, "images\\turnip.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Green Chilly", 30, "images\\green_chilly.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Lentil", 30, "images\\lentil.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Tinda", 30, "images\\tinda.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pumpkin", 30, "images\\pumpkin.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Brinjal", 30, "images\\brinjal.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cucumber", 30, "images\\cucumber.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Kidney Beans", 30, "images\\kidney_beans.png");