INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Apple", 10, "images\\apple.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Avocado", 15, "images\\avocado.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Blackberry", 10, "images\\blackberry.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Banana",15, "images\\banana.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Blueberry", 20, "images\\blueberry.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Date", 25, "images\\date.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Fig", 10, "images\\fig.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Grape", 30, "images\\grape.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Guava", 10, "images\\guava.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Jackfruit", 20, "images\\jackfruit.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Kiwifruit",40, "images\\kiwifruit.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Lemon", 25, "images\\lemon.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mango", 30, "images\\mango.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Orange", 35, "images\\orange.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Papaya", 20, "images\\papaya.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pineapple", 20, "images\\pineapple.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Peach", 20, "images\\peach.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Plum", 20, "images\\plum.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Strawberry", 20, "images\\strawberry.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Vanilla", 20, "images\\vanilla.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Watermelon", 20, "images\\watermelon.png");