INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Broccoli", 10, "images\\broccoli.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cabbage", 15, "images\\cabbage.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cauliflower", 10, "images\\cauliflower.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Chickpea",15, "images\\chickpea.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Onion", 20, "images\\onion.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Tomato", 25, "images\\tomato.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Radish", 10, "images\\radish.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Carrot", 30, "images\\carrot.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Potato", 30, "images\\potato.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mushroom", 30, "images\\mushroom.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Spinach", 30, "images\\spinach.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Garlic", 30, "images\\garlic.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Ginger", 30, "images\\ginger.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Capsicum", 30, "images\\capsicum.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Turnip", 30, "images\\turnip.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Green Chilly", 30, "images\\green_chilly.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Lentil", 30, "images\\lentil.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Tinda", 30, "images\\tinda.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pumpkin", 30, "images\\pumpkin.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Brinjal", 30, "images\\brinjal.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cucumber", 30, "images\\cucumber.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Kidney Beans", 30, "images\\kidney_beans.png");