INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Black Tea", 10, "images\\black_tea.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Coca Cola", 10, "images\\coca_cola.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Coffee", 15, "images\\coffee.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Fanta", 10, "images\\fanta.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Frooti",15, "images\\frooti.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Green Tea", 20, "images\\green_tea.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Limca", 25, "images\\limca.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mirinda", 10, "images\\mirinda.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mountain Dew", 30, "images\\mountain_dew.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Mazaa", 10, "images\\mazaa.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pepsi", 20, "images\\pepsi.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Red Bull",40, "images\\red_bull.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Sprite", 25, "images\\sprite.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Thumbs Up", 30, "images\\thumbs_up.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Soda", 35, "images\\soda.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Water", 20, "images\\water.png");