INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Biscuit", 10, "images\\biscuit.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Brownie", 15, "images\\brownie.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cake", 10, "images\\cake.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Casserole",15, "images\\casserole.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cookie", 20, "images\\CookieProxypng");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Cracker", 25, "images\\cracker.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Custard", 10, "images\\custard.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pastry", 30, "images\\pastry.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pie", 10, "images\\pie.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Pudding", 10, "images\\pudding.png");
INSERT INTO tbl_product (productName, quantity, productImage) VALUE ( "Tart", 5, "images\\tart.png");